//This file was autogenerated by bin/generate-schemas.py
import { Attribute } from 'src/core/mapper/decorators';
import { NamedAPIResource } from './named-api-resource';

export class PokemonHeldItemVersion {
  @Attribute()
  version: NamedAPIResource;

  @Attribute()
  rarity: number;
}
