//This file was autogenerated by bin/generate-schemas.py
import { Attribute } from 'src/core/mapper/decorators';
import { NamedAPIResource } from './named-api-resource';

export class PokemonStat {
  @Attribute()
  stat: NamedAPIResource;

  @Attribute()
  effort: number;

  @Attribute({ name: 'base_stat' })
  baseStat: number;
}
