//This file was autogenerated by bin/generate-schemas.py
import { Attribute } from 'src/core/mapper/decorators';
import { NamedAPIResource } from './named-api-resource';
import { PokemonMoveVersion } from './pokemon-move-version';

export class PokemonMove {
  @Attribute()
  move: NamedAPIResource;

  @Attribute({ name: 'version_group_details', items: PokemonMoveVersion })
  versionGroupDetails: Array<PokemonMoveVersion>;
}
