//This file was autogenerated by bin/generate-schemas.py
import { Attribute } from 'src/core/mapper/decorators';
import { NamedAPIResource } from './named-api-resource';
import { PokemonType } from './pokemon-type';

export class PokemonTypePast {
  @Attribute()
  generation: NamedAPIResource;

  @Attribute({ items: PokemonType })
  types: Array<PokemonType>;
}
