//This file was autogenerated by bin/generate-schemas.py
import { Attribute } from 'src/core/mapper/decorators';
import { NamedAPIResource } from './named-api-resource';
import { PokemonHeldItemVersion } from './pokemon-held-item-version';

export class PokemonHeldItem {
  @Attribute()
  item: NamedAPIResource;

  @Attribute({ name: 'version_details', items: PokemonHeldItemVersion })
  versionDetails: Array<PokemonHeldItemVersion>;
}
