//This file was autogenerated by bin/generate-schemas.py
import { Attribute } from 'src/core/mapper/decorators';
import { NamedAPIResource } from './named-api-resource';

export class VersionGameIndex {
  @Attribute({ name: 'game_index' })
  gameIndex: number;

  @Attribute()
  version: NamedAPIResource;
}
