//This file was autogenerated by bin/generate-schemas.py
import { ObjectSchema } from 'src/core/mapper/mapper.service';

const schema: ObjectSchema = {
  properties: {
    name: {
      type: 'string',
    },

    url: {
      type: 'string',
      format: 'url',
    },
  },
};
export default schema;
