//This file was autogenerated by bin/generate-schemas.py
import { ObjectSchema } from 'src/core/mapper/mapper.service';
import pokemonAbilitySchema from './pokemon-ability';
import namedAPIResourceSchema from './named-api-resource';
import versionGameIndexSchema from './version-game-index';
import pokemonHeldItemSchema from './pokemon-held-item';
import pokemonMoveSchema from './pokemon-move';
import pokemonTypePastSchema from './pokemon-type-past';
import pokemonSpritesSchema from './pokemon-sprites';
import pokemonStatSchema from './pokemon-stat';
import pokemonTypeSchema from './pokemon-type';

const schema: ObjectSchema = {
  properties: {
    id: {
      type: 'integer',
    },

    name: {
      type: 'string',
    },

    base_experience: {
      type: 'integer',
    },

    height: {
      type: 'integer',
    },

    is_default: {
      type: 'boolean',
    },

    order: {
      type: 'integer',
    },

    weight: {
      type: 'integer',
    },

    abilities: {
      items: pokemonAbilitySchema,
    },

    forms: {
      items: namedAPIResourceSchema,
    },

    game_indices: {
      items: versionGameIndexSchema,
    },

    held_items: {
      items: pokemonHeldItemSchema,
    },

    location_area_encounters: {
      type: 'string',
      format: 'url',
    },

    moves: {
      items: pokemonMoveSchema,
    },

    past_types: {
      items: pokemonTypePastSchema,
    },

    sprites: pokemonSpritesSchema,

    species: namedAPIResourceSchema,

    stats: {
      items: pokemonStatSchema,
    },

    types: {
      items: pokemonTypeSchema,
    },
  },
};
export default schema;
