//This file was autogenerated by bin/generate-schemas.py
import { ObjectSchema } from 'src/core/mapper/mapper.service';

const schema: ObjectSchema = {
  properties: {
    front_default: {
      type: 'string',
      format: 'url',
    },

    front_shiny: {
      type: 'string',
      format: 'url',
    },

    front_female: {
      type: 'string',
      format: 'url',
    },

    front_shiny_female: {
      type: 'string',
      format: 'url',
    },

    back_default: {
      type: 'string',
      format: 'url',
    },

    back_shiny: {
      type: 'string',
      format: 'url',
    },

    back_female: {
      type: 'string',
      format: 'url',
    },

    back_shiny_female: {
      type: 'string',
      format: 'url',
    },
  },
};
export default schema;
