//This file was autogenerated by bin/generate-schemas.py
import { ObjectSchema } from 'src/core/mapper/mapper.service';
import namedAPIResourceSchema from './named-api-resource';

const schema: ObjectSchema = {
  properties: {
    stat: namedAPIResourceSchema,

    effort: {
      type: 'integer',
    },

    base_stat: {
      type: 'integer',
    },
  },
};
export default schema;
