//This file was autogenerated by bin/generate-schemas.py
import { ObjectSchema } from 'src/core/mapper/mapper.service';
import namedAPIResourceSchema from './named-api-resource';
import pokemonHeldItemVersionSchema from './pokemon-held-item-version';

const schema: ObjectSchema = {
  properties: {
    item: namedAPIResourceSchema,

    version_details: {
      items: pokemonHeldItemVersionSchema,
    },
  },
};
export default schema;
