//This file was autogenerated by bin/generate-schemas.py
import { ObjectSchema } from 'src/core/mapper/mapper.service';
import namedAPIResourceSchema from './named-api-resource';
import pokemonTypeSchema from './pokemon-type';

const schema: ObjectSchema = {
  properties: {
    generation: namedAPIResourceSchema,

    types: {
      items: pokemonTypeSchema,
    },
  },
};
export default schema;
