//This file was autogenerated by bin/generate-schemas.py
import { ObjectSchema } from 'src/core/mapper/mapper.service';
import namedAPIResourceSchema from './named-api-resource';
import pokemonMoveVersionSchema from './pokemon-move-version';

const schema: ObjectSchema = {
  properties: {
    move: namedAPIResourceSchema,

    version_group_details: {
      items: pokemonMoveVersionSchema,
    },
  },
};
export default schema;
