//This file was autogenerated by bin/generate-schemas.py
import { ObjectSchema } from 'src/core/mapper/mapper.service';
import namedAPIResourceSchema from './named-api-resource';

const schema: ObjectSchema = {
  properties: {
    game_index: {
      type: 'integer',
    },

    version: namedAPIResourceSchema,
  },
};
export default schema;
